runtime: php55
api_version: 1
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: '.*'
    script: index.php
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
